# Copyright (c) 2025 ByteDance Ltd. and/or its affiliates.
# Copyright (c) ByteDance Ltd. and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import random
import unittest
from functools import reduce, wraps
from itertools import accumulate
from pathlib import Path
from string import ascii_letters
from typing import Optional

import pyarrow
import pyarrow.parquet as parquet
import pypaimon
import pybolt

from pybolt.test.utils import (
    StringGenerator,
    IntGenerator,
    RowVectorGenerator,
)

from ..executor.base import Executor
from ..plan_builder.base import PlanBuilderFactory
from ..catalog import PaimonOptions
from ..catalog.paimon import PaimonTable, PaimonMergeEngine, PaimonTimestamp
from ..dataframe import DataFrame
from ..details import FileUtils
from ..expression import NumProjectExpression, Expression

from .utils import Runtime

random.seed(os.getenv("SEED", 0))


def colPredicate(colName: str, colType: pybolt.BoltType = pybolt.BigintType()):
    return NumProjectExpression(Expression(colName, colType, None))


class DataFrameGenerator:
    def __init__(
        self,
        planFactory: PlanBuilderFactory,
        executor: Executor,
        generators=None,
    ):
        if generators is None:
            rng = random.Random(os.getenv("SEED", 0))
            generators = {
                "part0": StringGenerator(rng=rng).setNumStrings(4),
                "part1": (
                    IntGenerator(pybolt.BigintType(), rng=rng).setMin(1).setMax(4)
                ),
                "val0": IntGenerator(pybolt.BigintType(), rng=rng),
                "pk0": StringGenerator(rng=rng).unique(),
                "pk1": IntGenerator(pybolt.BigintType(), rng=rng).setMin(1).unique(),
            }
        self.__generator = RowVectorGenerator(**generators)
        self.__executor = executor
        self.__planFactory = planFactory

    def makeDataframe(self, size: int = 32) -> DataFrame:
        return DataFrame(
            self.__generator(size),
            executor=self.__executor,
            planFactory=self.__planFactory,
        ).orderBy(["pk0", "pk1"])

    def alterDataframe(
        self, df: DataFrame, numRows: int, columns: list[str] = ["val0"]
    ) -> DataFrame:
        """
        Make random updates in `columns` of the DataFrame `df` generated by
        this generator.
        """
        rows = list(range(len(df)))
        random.shuffle(rows)
        for i in rows[:numRows]:
            for col in columns:
                df[i, col] = self.__generator[col].generate_one()

        return df.orderBy(["pk0", "pk1"])

    @staticmethod
    def partitionDataframe(df, partitionKeys: list[str]) -> list[DataFrame]:
        if len(partitionKeys) == 0:
            return [df]

        df.orderBy(partitionKeys)
        partitions = []
        rowIndex = 0
        basePartValue = [df[0, col] for col in partitionKeys]
        for i in range(1, len(df)):
            partValue = [df[i, col] for col in partitionKeys]
            if partValue != basePartValue:
                partitions.append(df[rowIndex:i, :])
                rowIndex = i
                basePartValue = partValue
        partitions.append(df[rowIndex:, :])
        return partitions


def generic_test(*args, **kwargs):
    """
    Decorator to run PaimontTest.__testGeneric__ with specific input parameters.
    """

    def decorator(test_fn):
        @wraps(test_fn)
        def wrapper(self):
            for i, runtime in enumerate(Runtime.all()):
                with self.subTest(str(runtime)):
                    if i > 0:
                        self.tearDown()
                        self.setUp()
                    self.__testGeneric__(
                        runtime.planFactory, runtime.executor, *args, **kwargs
                    )

        return wrapper

    return decorator


class PaimonTest(unittest.TestCase):
    def setUp(self):
        randStr = StringGenerator(characters=ascii_letters).generate_one()
        self.pathPrefix = Path(os.path.realpath("."))
        self.dbName = "boltml-paimon"
        self.warehouseName = f"data-{randStr}"
        self.pypaimonCatalog = pypaimon.CatalogFactory().create(
            {"warehouse": str(self.warehousePath)}
        )
        try:
            self.pypaimonCatalog.create_database(self.dbName, False)
        except Exception:
            self.arrowFS.delete_dir(str(self.warehousePath))
            self.pypaimonCatalog.create_database(self.dbName, False)

    def tearDown(self):
        self.arrowFS.delete_dir(str(self.warehousePath))

    @property
    def arrowFS(self) -> pyarrow.fs.FileSystem:
        return pyarrow.fs.FileSystem.from_uri(self.dbPath)[0]

    @property
    def warehousePath(self) -> Path:
        return self.pathPrefix / self.warehouseName

    @property
    def dbPath(self) -> Path:
        return (
            self.warehousePath
            / f"{self.dbName}{pypaimon.catalog.catalog.Catalog.DB_SUFFIX}"
        )

    def tablePath(self, tableName: str) -> Path:
        return self.dbPath / tableName

    def tableIdentifier(self, tableName: str) -> str:
        return f"{self.dbName}.{tableName}"

    def fixTableFile(self, fpath: str, primaryKeys: list[str]):
        # pypaimon adds the columns "_SEQUENCE_NUMBER" and
        # "_VALUE_KIND" to the parquet files. However, it
        # does not add the columns "_KEY_<pk>". This column is required at least
        # with the merge engine in this test. We cannot simply
        # add the latter to the record batch above because they would
        # appear after the former. Bolt paimon reader requires that
        # "_KEY_<pk>" appear first.
        # Below we read the files and overwrite them with the new columns
        #
        # Additionally, bolt paimon split reader expects the column
        # `_VALUE_KIND` to be of type `int8_t` whereas pypaimon writes it as
        # `int32_t`. The spec says it should be a tinyinttype so we need this
        # workaround in tests.
        # Add primary key columns.
        t = parquet.read_table(self.arrowFS.open_input_file(fpath))
        self.arrowFS.delete_file(fpath)
        for i, pk in enumerate(primaryKeys):
            pkName = f"_KEY_{pk}"
            if pkName in t.column_names:
                continue
            column = next(c for c, n in zip(t.columns, t.column_names) if n == pk)
            t = t.add_column(i, pkName, column)

        # Cast "_VALUE_KIND" column to int8_t
        i, col, name = next(
            (
                (i, col, name)
                for (i, (col, name)) in enumerate(zip(t.columns, t.column_names))
                if name == "_VALUE_KIND"
            )
        )
        col = col.cast(pyarrow.int8())
        t = t.set_column(i, name, col)

        # Write final table.
        parquet.write_table(t, self.arrowFS.open_output_stream(fpath))

    def fixTableFiles(self, tableName, primaryKeys: list[str]):
        for fpath in FileUtils.listFiles(str(self.tablePath(tableName))):
            if fpath.endswith(".parquet"):
                self.fixTableFile(fpath, primaryKeys)

    def writeBatch(
        self,
        batch: DataFrame,
        tableName: str,
        partitionOverwrite: Optional[dict] = None,
    ):
        record_batch = pyarrow.RecordBatch.from_struct_array(batch.toArrow())
        table = self.pypaimonCatalog.get_table(self.tableIdentifier(tableName))
        write_builder = table.new_batch_write_builder()
        if partitionOverwrite is not None:
            write_builder = write_builder.overwrite(partitionOverwrite)
        table_write = write_builder.new_write()
        table_commit = write_builder.new_commit()
        table_write.write_arrow_batch(record_batch)
        commit_messages = table_write.prepare_commit()
        table_commit.commit(commit_messages)
        table_write.close()
        table_commit.close()

    def createTable(
        self,
        tableName: str,
        batches: list[DataFrame],
        overwrites: list[DataFrame] = [],
        partitionKeys: list[str] = [],
        primaryKeys: list[str] = [],
        numBuckets: int = -1,
        bucketKey: Optional[str] = None,
        fileFormat: pybolt.FileFormat = pybolt.FileFormat.PARQUET,
        mergeEngine: Optional[PaimonMergeEngine] = None,
        parameters: dict[str, str] = {},
    ):
        if len(overwrites) > 0 and len(partitionKeys) == 0:
            raise ValueError("Table overwrites require partitions.")
        if len(overwrites) > 0 and len(primaryKeys) == 0:
            raise ValueError(
                "Cannot overwrite append-only tables. You need primaryKeys."
            )

        hiveFileFormat = str(fileFormat).split(".")[-1].lower()
        parameters |= {
            pypaimon.common.core_options.CoreOptions.FILE_FORMAT: hiveFileFormat,
            pypaimon.common.core_options.CoreOptions.BUCKET: numBuckets,
        }
        if len(primaryKeys) > 0:
            parameters["primary-key"] = ",".join(primaryKeys)
        if mergeEngine is not None:
            parameters["merge-engine"] = mergeEngine.value
        if bucketKey is not None:
            parameters[pypaimon.common.core_options.CoreOptions.BUCKET_KEY] = bucketKey

        # Create paimon metadatas for the table
        arrow_schema = pyarrow.RecordBatch.from_struct_array(
            batches[0][0, :].toArrow()
        ).schema
        paimon_schema = pypaimon.Schema.from_pyarrow_schema(
            pa_schema=arrow_schema,
            partition_keys=partitionKeys,
            primary_keys=primaryKeys,
            options=parameters,
        )
        self.pypaimonCatalog.create_table(
            self.tableIdentifier(tableName),
            schema=paimon_schema,
            ignore_if_exists=False,
        )

        # Write batches to storage.
        for batch in batches:
            self.writeBatch(batch, tableName)

        # Splits overwrite batches in partitions and write them.
        def overwrite(batch, partitionKeys):
            for part in DataFrameGenerator.partitionDataframe(batch, partitionKeys):
                partitionOverwrite = {pk: part[0, pk] for pk in partitionKeys}
                self.writeBatch(part, tableName, partitionOverwrite)

        for batch in overwrites:
            overwrite(batch, partitionKeys)

        # If overwrite were applied, restore the initial values in the stored
        # table.
        if len(overwrites) > 0:
            df = reduce(
                lambda lhs, rhs: lhs.append(rhs.copy()), batches[1:], batches[0].copy()
            )
            overwrite(df, partitionKeys)

        # If tables has primary keys, they need fixing.
        # See `fixTableFile()`
        if len(primaryKeys) > 0:
            self.fixTableFiles(tableName, primaryKeys)

    def __testGeneric__(
        self,
        planFactory: PlanBuilderFactory,
        executor: Executor,
        tableName="paimontesttable",
        batchSizes: list[int] = [8],
        overwrites: list[int] = [],
        partitionKeys: list[str] = [],
        primaryKeys: list[str] = [],
        numBuckets: int = -1,
        bucketKey: Optional[str] = None,
        options: PaimonOptions = PaimonOptions(),
        transformExpectedDataframe=lambda df: df,
    ):
        dataGen = DataFrameGenerator(planFactory, executor)
        df = dataGen.makeDataframe(sum(batchSizes))
        batches = [
            df[offset : (offset + size), :]
            for offset, size in zip(accumulate([0] + batchSizes), batchSizes)
        ]
        overwrites = [
            dataGen.alterDataframe(df.copy(), numRows) for numRows in overwrites
        ]
        expectedDf = transformExpectedDataframe(df.copy()).orderBy(df.names)
        if len(expectedDf) == 0:
            raise ValueError(
                "Expected DataFrame is empty. This is likely a test logic error."
            )

        self.createTable(
            tableName,
            batches,
            overwrites,
            partitionKeys=partitionKeys,
            primaryKeys=primaryKeys,
            numBuckets=numBuckets,
            bucketKey=bucketKey,
            mergeEngine=options.mergeEngine,
        )

        resultDf = PaimonTable(str(self.tablePath(tableName))).read(options)
        resultDf = resultDf.orderBy(resultDf.names)

        if resultDf != expectedDf:
            print("Dataframe result mismatch!")
            print("Expected")
            print(expectedDf)
            print("Actual")
            print(resultDf)
        self.assertEqual(expectedDf, resultDf)

    @generic_test
    def testAppendOnlyTableSingleWrite(self): ...

    @generic_test(batchSizes=[8, 8])
    def testAppendOnlyTableMultipleAppends(self): ...

    @generic_test(numBuckets=3)
    def testAppendOnlyTableWithBuckets(self): ...

    @generic_test(numBuckets=3, bucketKey="part1")
    def testAppendOnlyTableWithNamedBuckets(self): ...

    @generic_test(partitionKeys=["part0", "part1"])
    def testAppendOnlyTableWithPartitions(self): ...

    @generic_test(
        # With a large batch, part==1 is unlikely to yield an empty test table.
        batchSizes=[128],
        partitionKeys=["part0", "part1"],
        options=PaimonOptions(
            partitionFilter=(
                (colPredicate("part1") == 1) & (colPredicate("part1") < 3)
            ),
        ),
        transformExpectedDataframe=lambda df: df.filter(
            (df["part1"] == 1) & (df["part1"] < 3)
        ),
    )
    def testAppendOnlyTableWithPartitionFilter(self): ...

    @generic_test(
        primaryKeys=["pk0", "pk1"],
        # pyPaimon requires buckets to write PrimaryKey tables.
        numBuckets=1,
    )
    def testPrimaryKeyTable(self): ...

    @generic_test(
        primaryKeys=["pk0", "pk1"],
        numBuckets=1,
        partitionKeys=["part0", "part1"],
    )
    def testPrimaryKeyTableWithPartitions(self): ...

    @generic_test(primaryKeys=["pk0", "pk1"], numBuckets=2, bucketKey="part1")
    def testPrimaryKeyTableWithNamedBuckets(self): ...

    @generic_test(
        batchSizes=[8, 8],
        primaryKeys=["pk0", "pk1"],
        numBuckets=1,
        partitionKeys=["part0"],
        overwrites=[8],
        bucketKey="part1",
    )
    def testPrimaryKeyTableWithPartitionsNamedBucketsAppendsAndOverwrites(self): ...

    @generic_test(
        batchSizes=[8, 8],
        primaryKeys=["pk0", "pk1"],
        numBuckets=1,
        partitionKeys=["part0"],
        overwrites=[8, 8, 8, 8],
        # Other merge engines are unlikely to work because the test wants and
        # assumes that pypaimon will give splits for the same table as the last
        # records update which is what DEDUPLICATE engine does.
        # Note that we don't really intend to test our merge engine
        # implementations but rather that we forward the right splits and
        # options to our paimon reader.
        options=PaimonOptions(mergeEngine=PaimonMergeEngine.DEDUPLICATE),
    )
    def testMergeEngineOption(self): ...

    @generic_test(
        batchSizes=[8],
        overwrites=[8],
        # Overwrites is on a partition basis.
        partitionKeys=["part0"],
        # Overwrites is for PrimaryKey tables.
        primaryKeys=["pk0", "pk1"],
        numBuckets=1,
        options=PaimonOptions(startTimestampMs=PaimonTimestamp.EARLIEST),
    )
    def testTimestampOption(self): ...
