version: '3.8'

services:
  base-runner:
    build: .
    restart: unless-stopped
    env_file:
      - variables.env
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /etc/hostname:/etc/host-hostname:ro
      - ${HOST_DATA_DIR}/conan-server-data:/data/conan-server-data:r
      - ${HOST_DATA_DIR}/pre-commit-cache:/data/pre-commit-cache
