# Copyright (c) ByteDance Ltd. and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import random
from abc import ABC, abstractmethod
from string import ascii_letters, digits, punctuation
from typing import Any

from pybolt import (
    ArrayType,
    BaseVector,
    BigintType,
    BoltType,
    BooleanType,
    DoubleType,
    HugeintType,
    IntegerType,
    MapType,
    RealType,
    RowType,
    RowVector,
    SmallintType,
    Timestamp,
    TimestampType,
    TinyintType,
    VarbinaryType,
    VarcharType,
    fromList,
    rowVector,
)


class ColumnGenerator(ABC):
    def __init__(self, rng=random):
        self.__rng = rng

    @staticmethod
    def from_dtype(dtype: BoltType, rng: random.Random = random) -> "ColumnGenerator":
        """
        Create a Bolt Vector generator that yields random values of the given data type.
        """
        if isinstance(dtype, BooleanType):
            generator = BooleanGenerator(rng=rng)
        elif isinstance(
            dtype,
            (BigintType, HugeintType, IntegerType, SmallintType, TinyintType),
        ):
            generator = IntGenerator(dtype, rng=rng)
        elif isinstance(dtype, VarcharType):
            generator = StringGenerator(rng=rng)
        elif isinstance(dtype, VarbinaryType):
            generator = BytesGenerator(rng=rng)
        elif isinstance(dtype, (RealType, DoubleType)):
            generator = FloatGenerator(dtype, rng=rng)
        elif isinstance(dtype, TimestampType):
            generator = TimestampGenerator(rng)
        elif isinstance(dtype, RowType):
            generators = {
                colName: ColumnGenerator.from_dtype(colType, rng)
                for colName, colType in (dtype[i] for i in range(dtype.size()))
            }
            generator = RowVectorGenerator(**generators)
        elif isinstance(dtype, ArrayType):
            generator = ArrayGenerator(
                3, ColumnGenerator.from_dtype(dtype.elementType(), rng)
            )
        elif isinstance(dtype, MapType):
            generator = MapGenerator(
                ColumnGenerator.from_dtype(dtype.keyType(), rng),
                ColumnGenerator.from_dtype(dtype.valueType(), rng),
            )
        else:
            raise ValueError(f"No random generator for data type: {dtype}")
        return generator

    @staticmethod
    def repeat(value: Any, dtype: BoltType | None = None) -> "ColumnGenerator":
        """
        Create a Column generator that repeats a value.
        """
        return RepeatGenerator(value, dtype)

    @property
    def rng(self) -> random.Random:
        return self.__rng

    @property
    @abstractmethod
    def dtype(self) -> BoltType:
        """
        Get the data type of the values generated by this generator.
        """
        ...

    def unique(self) -> "ColumnGenerator":
        """
        Transform this generator into a generator that returns random distinct values.
        """
        return UniqueValuesGenerator(self)

    def with_none_values(self) -> "ColumnGenerator":
        """
        Transform this generator into a generator that contains None/null values.
        """
        return NoneValuesGenerator(self)

    def __call__(self, *args):
        if not args:
            return self.generate_one()
        elif isinstance(args[0], int):
            return self.generate_vector(args[0])
        else:
            raise TypeError(
                "ColumnGenerator expects either 0 arguments to generate a "
                "single value or one integer argument to generate a BaseVector."
            )

    @abstractmethod
    def generate_list(self, length: int) -> list: ...

    def generate_vector(self, length: int) -> BaseVector:
        """
        Generate `length` values stored in a Bolt `BaseVector`.
        """
        return fromList(self.generate_list(length), self.dtype)

    def generate_one(self) -> Any:
        """
        Generate a single value.
        """
        return self.generate_list(1)[0]


class UniqueValuesGenerator(ColumnGenerator):
    def __init__(self, generator: ColumnGenerator):
        self.__generator = generator
        super().__init__(generator.rng)

    @property
    def dtype(self) -> BoltType:
        return self.__generator.dtype

    def generate_list(self, length) -> list:
        values = set(self.__generator.generate_list(length))
        while len(values) < length:
            values |= set(self.__generator.generate_list(length - len(values)))
        return list(values)


class RepeatGenerator(ColumnGenerator):
    def __init__(self, value: Any, dtype: BoltType | None = None):
        if dtype is None:
            dtype = fromList([value]).dtype()
        self.__dtype = dtype
        self.__value = value
        super().__init__()

    @property
    def dtype(self) -> BoltType:
        return self.__dtype

    def generate_list(self, length: int) -> list:
        return [self.__value for _ in range(length)]


class NoneValuesGenerator(ColumnGenerator):
    def __init__(self, generator: ColumnGenerator):
        self.__generator = generator
        super().__init__(generator.rng)

    @property
    def dtype(self) -> BoltType:
        return self.__generator.dtype

    def generate_list(self, length: int) -> list:
        values = self.__generator.generate_list(length)
        if length == 1:
            numNulls = 0
        else:
            numNulls = self.rng.randint(1, length - 1)
        indices = list(range(length))
        for _ in range(numNulls):
            index = self.rng.choice(range(len(indices)))
            values[indices[index]] = None
            indices.pop(index)
        return values

    def generate_vector(self, length: int) -> BaseVector:
        values = self.__generator.generate_vector(length)
        if length == 1:
            numNulls = 0
        else:
            numNulls = self.rng.randint(1, length - 1)

        def getVectors(values: BaseVector):
            vectors = [values]
            if not isinstance(values, RowVector):
                return vectors
            for vec in (values.childAt(n) for n in values.dtype().names()):
                vectors += getVectors(vec)
            return vectors

        vectors = getVectors(values)
        indices = list(range(length))
        for _ in range(numNulls):
            index = self.rng.choice(range(len(indices)))
            for vec in vectors:
                vec.setNull(indices[index])
            indices.pop(index)
        return values


class ArrayGenerator(ColumnGenerator):
    def __init__(self, element_size: int, generator: ColumnGenerator):
        if isinstance(generator.dtype, (ArrayType, MapType, RowType)):
            raise ValueError("ArrayGenerator does not support complex type generators.")
        self.__element_size = element_size
        self.__generator = generator
        super().__init__(generator.rng)

    @property
    def dtype(self) -> BoltType:
        return ArrayType(self.__generator.dtype)

    def generate_list(self, length: int) -> list:
        return [
            self.__generator.generate_list(self.__element_size) for _ in range(length)
        ]


class MapGenerator(ColumnGenerator):
    def __init__(self, keys: ColumnGenerator, values: ColumnGenerator):
        complex_types = (ArrayType, MapType, RowType)
        if isinstance(keys.dtype, complex_types) or isinstance(
            values.dtype, complex_types
        ):
            raise ValueError("MapGenerator does not support complex type generators.")
        self.__key_generator = keys
        self.__value_generator = values
        super().__init__(keys.rng)

    @property
    def dtype(self) -> BoltType:
        return MapType(self.__key_generator.dtype, self.__value_generator.dtype)

    def generate_list(self, length: int) -> list:
        return [
            {self.__key_generator.generate_one(): self.__value_generator.generate_one()}
            for _ in range(length)
        ]


class RowVectorGenerator(ColumnGenerator):
    def __init__(self, **generators: dict[str, ColumnGenerator]):
        self.__names = []
        self.__generators = []
        for n, g in generators.items():
            self.__names.append(n)
            self.__generators.append(g)
        super().__init__(next(iter(generators.values())).rng)

    def __getitem__(self, col: str) -> ColumnGenerator:
        index = next((i for i, n in enumerate(self.__names) if n == col), None)
        if index is None:
            raise KeyError("No column named {col} in RowVectorGenerator.")
        return self.__generators[index]

    def appendColumn(self, name: str, generator: ColumnGenerator) -> "Self":  # noqa: F821
        self.__names.append(name)
        self.__generators.append(generator)
        return self

    @property
    def dtype(self) -> BoltType:
        return RowType(self.__names, [g.dtype for g in self.__generators])

    def generate_list(self, length: int) -> list:
        rows = []
        for _ in range(length):
            values = [g.generate_vector(1) for g in self.__generators]
            rows.append(rowVector(self.__names, values))
        return rows

    def generate_vector(self, length: int) -> BaseVector:
        columns = [g.generate_vector(length) for g in self.__generators]
        return rowVector(self.__names, columns)


class BooleanGenerator(ColumnGenerator):
    @property
    def dtype(self) -> BoltType:
        return BooleanType()

    def generate_list(self, length: int) -> list:
        return [self.rng.choice([True, False]) for _ in range(length)]


class IntGenerator(ColumnGenerator):
    def __init__(self, dtype: BoltType = IntegerType(), rng: random.Random = random):
        if isinstance(dtype, TinyintType):
            self.__max = (1 << 7) - 1
            self.__min = -1 * self.__max
        elif isinstance(dtype, SmallintType):
            self.__max = (1 << 15) - 1
            self.__min = -1 * self.__max
        elif isinstance(dtype, IntegerType):
            self.__max = (1 << 31) - 1
            self.__min = -1 * self.__max
        elif isinstance(dtype, BigintType):
            # Cast from python `int` to C++ `long` fails for values greater
            # that that.
            self.__max = (1 << 61) - 1
            self.__min = -1 * self.__max
        elif isinstance(dtype, HugeintType):
            self.__max = (1 << 127) - 1
            self.__min = -1 * self.__max
        else:
            raise TypeError(f"Invalid integer type: {dtype}.")
        self.__dtype = dtype
        super().__init__(rng)

    def setMax(self, value: int) -> "Self":  # noqa: F821
        if self.__min is not None and value < self.__min:
            raise ValueError(
                f"IntGenerator max value {value} cannot be less than min value"
                f" {self.__min}."
            )
        self.__max = value
        return self

    def setMin(self, value: int) -> "Self":  # noqa: F821
        if self.__max is not None and value > self.__max:
            raise ValueError(
                f"IntGenerator min value {value} cannot be more than max value"
                f" {self.__max}."
            )
        self.__min = value
        return self

    @property
    def dtype(self) -> BoltType:
        return self.__dtype

    def generate_list(self, length: int) -> list:
        if self.__min == self.__max:
            return [self.__min for _ in range(length)]
        else:
            return [self.rng.randint(self.__min, self.__max) for _ in range(length)]


class StringGenerator(ColumnGenerator):
    def __init__(
        self,
        length: int = 8,
        fixedLength=False,
        characters: str = ascii_letters + digits + punctuation,
        rng: random.Random = random,
    ):
        self.__length = length
        self.__fixedLength = fixedLength
        self.__choices = []
        self.__numStrings = None
        self.__characters = characters
        super().__init__(rng)

    def setLength(self, length: int) -> "Self":  # noqa: F821
        self.__length = length
        self.__choices = []
        return self

    def setFixedLength(self, fixedLength: bool) -> "Self":  # noqa: F821
        self.__fixedLength = fixedLength
        self.__choices = []
        return self

    def setNumStrings(self, num: int) -> "Self":  # noqa: F821
        self.__numStrings = num
        self.__choices = []
        return self

    @property
    def dtype(self) -> BoltType:
        return VarcharType()

    def __generate(self, length: int) -> list[str]:
        return [
            "".join(
                self.rng.choice(self.__characters)
                for _ in range(
                    self.__length
                    if self.__fixedLength
                    else self.rng.randint(0, self.__length)
                )
            )
            for _ in range(length)
        ]

    def generate_list(self, length: int) -> list:
        if self.__numStrings is not None and len(self.__choices) == 0:
            self.__choices = self.__generate(self.__numStrings)
        if self.__numStrings is not None:
            return [self.rng.choice(self.__choices) for _ in range(length)]
        else:
            return self.__generate(length)


class BytesGenerator(ColumnGenerator):
    def __init__(self, length: int = 8, fixedLength=False, rng: random.Random = random):
        self.__length = length
        self.__fixedLength = fixedLength
        super().__init__(rng)

    def setLength(self, length: int) -> "Self":  # noqa: F821
        self.__length = length
        return self

    def setFixedLength(self, fixedLength: bool) -> "Self":  # noqa: F821
        self.__fixedLength = fixedLength
        return self

    @property
    def dtype(self) -> BoltType:
        return VarbinaryType()

    def generate_list(self, length: int) -> list:
        return [
            self.rng.randbytes(
                self.__length
                if self.__fixedLength
                else self.rng.randint(0, self.__length)
            )
            for _ in range(length)
        ]


class FloatGenerator(ColumnGenerator):
    def __init__(self, floatType=RealType(), rng: random.Random = random):
        if not isinstance(floatType, (DoubleType, RealType)):
            raise TypeError(f"Invalid float type: {floatType}.")
        self.__dtype = floatType
        super().__init__(rng)

    @property
    def dtype(self) -> BoltType:
        return self.__dtype

    def generate_list(self, length: int) -> list:
        return [self.rng.random() for _ in range(length)]


class TimestampGenerator(ColumnGenerator):
    def __init__(self, rng: random.Random = random):
        boltMinSec = -1 * (1 << 33) // 1000 - 1
        boltMaxSec = (1 << 33) // 1000 - 1
        boltMaxNanos = 999999999
        self.__secs_generator = (
            IntGenerator(BigintType(), rng=rng).setMin(boltMinSec).setMax(boltMaxSec)
        )
        self.__nanos_generator = (
            IntGenerator(BigintType(), rng=rng).setMin(0).setMax(boltMaxNanos)
        )
        super().__init__(rng)

    @property
    def dtype(self) -> BoltType:
        return TimestampType()

    def generate_list(self, length: int) -> list:
        return [
            Timestamp(
                self.__secs_generator.generate_one(),
                self.__nanos_generator.generate_one(),
            )
            for _ in range(length)
        ]


ALL_BOLT_TYPES_ROW_TYPE = RowType(
    *tuple(
        map(
            list,
            zip(
                *[
                    ("c_bool", BooleanType()),
                    ("c_tinyint", TinyintType()),
                    ("c_smallint", SmallintType()),
                    ("c_int", IntegerType()),
                    ("c_bigint", BigintType()),
                    ("c_real", RealType()),
                    ("c_double", DoubleType()),
                    ("c_timestamp", TimestampType()),
                    ("c_varchar", VarcharType()),
                    ("c_varbinary", VarbinaryType()),
                    ("c_array", ArrayType(IntegerType())),
                    ("c_map", MapType(VarcharType(), IntegerType())),
                    ("c_row", RowType(["nested_int"], [IntegerType()])),
                ]
            ),
        )
    )
)
